# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.CURRENT_IMAGE_TAG }}
    steps:
      - name: Get current image tag
        id: step1
        run: eccho "CURRENT_IMAGE_TAG=`date`" >> "$GITHUB_OUTPUT"
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    
      - name: do random 
        if: ${{ failure() && steps.step1.output == 'failure' }}
        run: echo `date`
        
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        if: ${{ failure() && steps.step1.output == 'failure' }}
        run: |
          echo "Today's date is $OUTPUT1"
          echo "We have a call on $OUTPUT1"
