name: vault

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  vault-secret:
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.dev.jackhenryorigin.com
          caCertificate: ${{ vars.DEV_OGN_SVCS_VAULT_CA_CERT }}
          method: github
          githubToken: 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
