name: execute-ddl-dml

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: /home/runner/work
    
env: 
  PY_SCRIPT_PATH: devops/execute-ddl-dml.py
  DDL_SCRIPT_PATH: devops/releases/mongo/ddl/ddl.js
  DML_SCRIPT_PATH: devops/releases/mongo/dml/dml.js 
  MONGO_CONNECTION_STRING: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.8.0

jobs:
  js-execution:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: bitnami/mongodb:latest
        ports:
          - 27017:27017
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Setup Mongosh & TLS Certificate Key File
        run: |
          cd `pwd`/hello
          wget https://downloads.mongodb.com/compass/mongosh-1.8.0-linux-x64.tgz
          tar -xvf mongosh-1.8.0-linux-x64.tgz
          ls -la
          pwd
          whoami
          chmod +x `pwd`/mongosh-1.8.0-linux-x64/bin/mongosh
          mv `pwd`/mongosh-1.8.0-linux-x64/bin/mongosh /usr/local/bin/mongosh
          ls /usr/local/bin/mongosh
          cd ..
          pwd
          touch `pwd`/tlsCertificateKeyFile.pem
