# Testing step to execute when files under a folder chnages

name: demo
on:
  workflow_dispatch:

jobs:
  conditional_step:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under scripts/ has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '^scripts/' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docs_changed"
        # Write-Host "::set-output name=docs_changed::$HasDiff"
        echo "docs_changed=$HasDiff" >> $GITHUB_ENV

    # Run the step only with "docs_changed" equals "True"
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: ${{ env.docs_changed == 'True' }}
      run: echo "Files changed!"
