# Testing step to execute when files under a folder chnages

name: demo
on:
  workflow_dispatch:

jobs:
  conditional_step:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
        
    - name: Run task only if specific folder is updated
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q '^scripts/'; then
          echo "files_changed=true" >> $GITHUB_ENV
        else
          echo "files_changed=false" >> $GITHUB_ENV
        fi
        
    - name: Check if files changed
      if: ${{ env.files_changed == 'true' }}
      run: echo "files changed"
