name: inline-bash

on:
  workflow_dispatch:

jobs:
  inline-bash:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2
      - name: Make a file
        run : |
            echo "Mukesh" > /tmp/sample.txt


      - name: Output
        run: echo "file_size=$(stat -c %s '/tmp/sample.txt')" >> $GITHUB_OUTPUT    
        
      - name: Check if statement
        if: ${{ env.file_size != 0 }}
        run: |
            echo "File is not empty."
              
