name: inline-bash

on:
  workflow_dispatch:

jobs:
  inline-bash:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2
      - name: Make a file
        run : |
            echo "Mukesh" > /tmp/sample.txt


      - name: Output
        id: output
        run: |
            echo "SIZE=`stat -c %s '/tmp/sample.txt'`" >> $GITHUB_OUTPUT
            
      - name: Print
        run: |
            echo "${{ step.output.outputs.SIZE }}"
              
