name: inline-bash

on:
  workflow_dispatch:

jobs:
  inline-bash:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2
      - name: Make a file
        run : |
            echo "" > /tmp/sample.txt


      - name: Output
        id: file_size
        run: |
            echo "size=`wc -l < '/tmp/sample.txt'`" >> $GITHUB_OUTPUT
            
      - name: Print
        if: ${{ steps.file_size.outputs.size != 0 }}
        run: |
            echo ${{ steps.file_size.outputs.size }}
            echo "File is not empty."
              
