name: inline-bash

on:
  workflow_dispatch:

jobs:
  inline-bash:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2
      - name: Make a file
        run : |
            echo "." > /tmp/stale_branch.txt


      - name: Output
        id: file_size
        run: |
            echo "size=`stat -c %s '/tmp/stale_branch.txt'`" >> $GITHUB_OUTPUT
            
      - name: Print
        if: ${{ steps.file_size.outputs.size > 1 }}
        run: |
            echo ${{ steps.file_size.outputs.size }}
            echo "File is not empty."
              
