name: ddl-and-dml-js-scripts-execution

on:
  workflow_dispatch:

env: 
  PY_SCRIPT_PATH: scripts/python/execute_ddl_and_dml_js_scripts.py 

jobs:
  js-execution:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      # In this step, we will execute the python script which will run the ddl and dml js scripts. 
        
      - name: Execute Py Script
        run: python ${{env.PY_SCRIPT_PATH}}
        env:
          MY_SECRET_USERNAME: ${{vars.MONGO_USERNAME}}

