name: ddl-and-dml-js-scripts-execution

on:
  workflow_dispatch:

env: 
  PY_SCRIPT_PATH: scripts/python/execute_ddl_and_dml_js_scripts.py 
  JS_PATH_1: scripts/javascripts/script1.js 
  JS_PATH_2: scripts/javascripts/script2.js 

jobs:
  js-execution:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: docker.io/mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Docker version
        run: |
          echo "CONTAINER_ID=$(docker ps -a | grep -i mongo:latest | awk '{print $1}') >> $GITHUB_ENV
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
          
      # In this step, we will execute the python script which will run the ddl and dml js scripts. 
        
      - name: Execute Py Script
        run: python ${{env.PY_SCRIPT_PATH}}
        env:
          MY_SECRET_USERNAME: ${{vars.MONGO_USERNAME}}
          JS_PATH_1: ${{env.JS_PATH_1}}
          JS_PATH_2: ${{env.JS_PATH_2}}
          CONTAINER_ID: ${{env.CONTAINER_ID}}

