name: Build

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - '**/main'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Redis
        run: docker run -d --network host -e "ALLOW_EMPTY_PASSWORD=yes" bitnami/redis:latest

      - name: Install Redis-cli
        run: |
          sudo apt install redis-tools --yes
          
      - name: Test connection
        run: redis-cli ping
