name: Notify About Stale Branches

on:
  schedule:
    - cron: "59 23 * * *"  # Triggers the workflow everyday at 11:59 PM
    
  workflow_dispatch:
  
jobs:
  DailyCronJob:
    runs-on: ubuntu-22.04
    name: Stale branch check
    steps:
      
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: MukeshSinghRawat/hello
        
      - name: PWD
        run: which git && pwd && ls

      - id: step1
        name: Branches having the last commit date older than a week
        run: |     
            echo { "Name": "Mukesh" } > /tmp/staticDataService.json
        continue-on-error: true
      
      - name: Send custom data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload-file-path: "/tmp/staticDataService.json"
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
