name: Notify About Stale Branches

on:
  schedule:
    - cron: "59 23 * * *"  # Triggers the workflow everyday at 11:59 PM
    
  workflow_dispatch:
  
jobs:
  DailyCronJob:
    runs-on: ubuntu-22.04
    name: Stale branch check
    steps:
      
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: MukeshSinghRawat/hello
          fetch-depth: 0
          set-safe-directory: false
          path: repo1
        
      - name: Check Stale Branches
        run: |
          ls && pwd
          cd repo1
          git branch -r --format="%(committerdate:iso8601), %(committerdate:relative) - %(refname:short)   [%(authorname)]" | grep -v HEAD | sort -r | grep -i "week\|month\|year" | grep -v origin/main
          git branch -r --format="%(committerdate:iso8601), %(committerdate:relative) - %(refname:short)   [%(authorname)]" | grep -v HEAD | sort -r | grep -i "week\|month\|year" | grep -v origin/main > /tmp/stale_branch.txt
        continue-on-error: true
      
      - name: ECHO
        run: cat /tmp/stale_branch.txt
        
      - name: Send custom data to Slack workflow
        run : |
          curl -X POST --data-urlencode "payload={\"channel\": \"#new-test\", \"username\": \"stale-branch-notifier\", \"text\": \"${{ env.STALE_BRANCH }}\"}" ${{ secrets.WEBHOOK_URL }}
