name: Notify About Stale Branches

on:
  schedule:
    - cron: "59 23 * * *"  # Triggers the workflow everyday at 11:59 PM
    
  workflow_dispatch:
  
jobs:
  DailyCronJob:
    runs-on: ubuntu-22.04
    name: Stale branch check
    steps:
      
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: MukeshSinghRawat/hello
        
      - name: PWD
        run: which git && pwd && ls

      - id: step1
        name: Branches having the last commit date older than a week
        run: |     
            echo {"Name":"Mukesh"} > /tmp/staticDataService.json
        continue-on-error: true
      
      - name: Send custom data to Slack workflow
        run : |
          curl -X POST --data-urlencode "payload={\"channel\": \"#new-test\", \"username\": \"Action-Notify\", \"text\": \"This is posted to #new-test and comes from a bot named webhookbot.\", \"icon_emoji\": \":ghost:\"}" ${{ secrets.WEBHOOK_URL }}
