name: vault

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  vault-secret:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2

      - name: Retrieve Secrets from Vault
        id: import-secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: https://vault.dev.jackhenryorigin.com
          caCertificate: ${{ vars.DEV_OGN_SVCS_VAULT_CA_CERT }}
          method: github
          githubToken: ${{ secrets.VAULT_PAT }}
          secrets: |
            secret/data/entityservices/static-data certPassword

          
