name: vault

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  vault-secret:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2

      - name: Retrieve Secrets from Vault
        id: import-secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: https://vault.dev.jackhenryorigin.com/ui/vault
          token: 'hvs.CAESILat89YjkzSl0vzjQlNYkF26YgAqeWETnb_pl0hvjBnUGh4KHGh2cy5jTXlKQ0dWTGVhU3IwVEtLekIxUksyQzM'
          caCertificate: ${{ vars.DEV_OGN_SVCS_VAULT_CA_CERT }}
          secrets: |
            secret/data/entityservices/static-data certPassword

          
