name: vault

on:
  workflow_dispatch:
    
env:
  vault_url: https://vault.dev.jackhenryorigin.com

jobs:
  vault-secret:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2
      - name: check pwd
        run : |
          ls -la
          pwd
          whoami

#       - name: Retrieve Secrets from Vault
#         id: import-secrets
#         uses: hashicorp/vault-action@v2.5.0
#         with:
#           url: ${{ env.vault_url }}
#           caCertificate: ${{ vars.DEV_OGN_SVCS_VAULT_CA_CERT }}
#           method: github
#           githubToken: ${{ inputs.github_token }}
#           secrets: | 
#             secret/data/entityservices/entity-static-data/mongo certPassword

#       - name: Print the Secret
#         run: |
#           touch secrets.json
#           echo "${{ toJson(steps.import-secrets.outputs) }}" >> secrets.json
