name: vault

on:
  workflow_dispatch:
    inputs:
      github_token: 
        description: 'GH PAT'
        required: true
        type: string


jobs:
  vault-secret:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2

      - name: Retrieve Secrets from Vault
        id: import-secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: https://vault.dev.jackhenryorigin.com
          caCertificate: ${{ vars.DEV_OGN_SVCS_VAULT_CA_CERT }}
          method: github
          githubToken: ${{ inputs.github_token }}
          secrets: | 
            secret/data/entityservices/entity-static-data/mongo certPassword

      - name: Print the Secret
        run: |
          touch secrets.json
          echo "${{ toJson(steps.import-secrets.outputs) }}" >> secrets.json
