name: vault

on:
  workflow_dispatch:

  push:
    branches:
      - get-secret-from-vault-br

jobs:
  vault-secret:
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.dev.jackhenryorigin.com
          token: 'hvs.CAESILat89YjkzSl0vzjQlNYkF26YgAqeWETnb_pl0hvjBnUGh4KHGh2cy5jTXlKQ0dWTGVhU3IwVEtLekIxUksyQzM'
          caCertificate: ${{ vars.DEV_OGN_SVCS_VAULT_CA_CERT }}
          secrets: |
            secret/entityservices/entity-static-data/Mongo certPassword | PASSWORD
      
      - name: Print the PASSWORD
        run: echo "${{ env.PASSWORD }}"
